name: Enderpay
version: ${project.version}
main: com.enderpay.Plugin
api-version: 1.17
description: Minecraft plugin for Enderpay
website: https://enderpay.com
commands:
  enderpay-setup:
    description: Setup API credentials
    usage: /<command> <api-key> <api-secret>
    permission: enderpay.admin
  enderpay-force:
    description: Check for new commands
    usage: /<command> force
    permission: enderpay.admin
  buy:
    description: Open server buy menu
    usage: /<command>
  enderpay-sync:
    description: Sync latest changes
    usage: /<command> sync
    permission: enderpay.admin
  enderpay-help:
    description: Get plugin related help
    usage: /<command> help
    permission: enderpay.admin